name: CI

on:
  push:
  schedule:
  - cron: '15 6 * * 3'

jobs:
  build:
    permissions:
      id-token: write
      contents: write

    runs-on: ubuntu-latest

    steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.17'

    - uses: actions/checkout@v2

    - name: Test
      run: make test

    - name: Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: goreleaser/goreleaser-action@v2
      with:
        version: latest
        args: release --rm-dist
      env:
        GITHUB_TOKEN: ${{ github.token }}
