name: CI

on:
  push:
  schedule:
  - cron: '15 6 * * 3'

jobs:
  build:
    permissions:
      id-token: write
      contents: read

    runs-on: ubuntu-latest

    steps:
    - name: Get credentials
      uses: hashicorp/vault-action@v2.4.0
      with:
        url: https://vault.jimdo-platform.net
        method: jwt
        role: wonderland_travis_migration
        secrets: |
          secret/wonderland/github-publish GITHUB_TOKEN ;

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.15.2'

    - uses: actions/checkout@v2

    - name: Test
      run: make test

    - name: Release
      run: test -n "$GITHUB_TAG" && make release
